# Extract the real port of the client request url (unfortunatly nginx has no variable to get this info)
map $http_host $request_port {
	default               443;
	"~^[^\:]+:(?<p>\d+)$" $p;
}

server {
	listen 80;
	server_name _;

	# Forward requests to other containers
	location /api {
		proxy_pass http://backend:8080;
	}

	location /logs {
		proxy_pass http://dozzle:8080;
	}

	location /adminer {
		proxy_pass http://adminer:8080;
	}

	location / {
		proxy_pass http://frontend:80;
	}

	# Include some data from the original request during the forwarding,
	# so the destination can know things like the original url or protocol
	proxy_set_header Host $http_host;
	proxy_set_header X-Forwarded-Host $http_host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Port $request_port;

	# Allow webhooks
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection "Upgrade";
}
