services:
  ingress:
    build: ./ingress
    image: "${INGRESS_IMAGE:-}"
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    ports:
      - "${INGRESS_PORT}:80"

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: products
      POSTGRES_PASSWORD: "${DB_APP_PASSWORD}"
      TZ: "America/Argentina/Buenos_Aires"
    volumes:
      - "${VOLUME_DIR}/data:/var/lib/postgresql/data"
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d products" ]
      timeout: 5s
      start_period: 1m
      start_interval: 10s
      interval: 1m
      retries: 5

  backend:
    build: ./backend
    image: "${BACKEND_IMAGE:-}"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SERVER_SERVLET_CONTEXT_PATH: /api
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "${DB_APP_PASSWORD}"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/products"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
      SPRING_LIQUIBASE_CONTEXTS: prod
      TZ: "America/Argentina/Buenos_Aires"
      JAVA_TOOL_OPTIONS: "-Duser.timezone=America/Argentina/Buenos_Aires"
      RESEND_API_KEY: "${RESEND_API_KEY}"
      FRONTEND_URL: "${FRONTEND_URL}"
    healthcheck:
      test: "curl --fail --silent http://localhost:8081/actuator/health | grep UP || exit 1"
      timeout: 5s
      start_period: 90s
      start_interval: 10s
      interval: 1m 
      retries: 5

  frontend:
    build: ./frontend
    image: "${FRONTEND_IMAGE:-}"
    depends_on:
      backend:
        condition: service_started
    environment:
      BACKEND_EXTERNAL_URL: "${EXTERNAL_URL}/api"

  adminer:
    image: adminer:5.4.0
    depends_on:
      db:
        condition: service_started
    ports:
      - "8082:8080"

  dozzle:
    image: amir20/dozzle
    volumes:
      - "${DOCKER_SOCKET}:/var/run/docker.sock"
    environment:
      DOZZLE_BASE: /logs
